# Generated by Django 5.0.4 on 2024-04-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendencesystem", "0002_rename_time_attendance_time_in_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="time_in",
            new_name="time",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="employee_name",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendencesystem.employee",
            ),
        ),
    ]
