# Generated by Django 5.0.4 on 2024-04-27 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendencesystem", "0003_rename_time_in_attendance_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="time",
            new_name="time_in",
        ),
    ]
