# Generated by Django 5.0.4 on 2024-04-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendencesystem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="time",
            new_name="time_in",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employee_id",
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
